spring:
  profiles:
    active: dev
  #开启restful风格
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB
  redis:
    host: 121.36.18.244
    password: 123456
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        min-idle: 0
  data:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1245325661@qq.com  #发送邮件的邮箱地址
    password: tcflcazgcasuihia  #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 1245325661@qq.com  # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

#系统的一些数据
AdminCode: "you are not Admin!"